### ISSUE TITLE
running sudo -u apache /usr/local/bin/ruby-300 jobs/update_migel_products_with_report throws an error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/migel#8]
![latest-screenshot](https://user-images.githubusercontent.com/4953/105850417-fe14fa00-5fe1-11eb-8021-c744028c2061.png)

**Comment by ngiger** [comment]
Probier mal, ob es mit 
`sudo -u apache bundle-300 exec ruby-300 jobs/update_migel_products_with_report`
durchläuft.

**Comment by zdavatz** [comment]
Das klappt auch nicht.

![latest-screenshot](https://user-images.githubusercontent.com/4953/105954978-d4a5ae00-6075-11eb-81ec-2506b1fdf435.png)

**Comment by zdavatz** [comment]
Nach einem 
1. `sudo svc -d /service/*`
2. Neustart von `Postgresql`
3. `sudo svc -u /service/*` klappt es.
